// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvl09IQ3Ed51Y3tNcz_PQkDMweLaXBqeE',
    appId: '1:425547129915:web:cf4dfe1e5a77f0e008e81e',
    messagingSenderId: '425547129915',
    projectId: 'btdemo-12eb1',
    authDomain: 'btdemo-12eb1.firebaseapp.com',
    storageBucket: 'btdemo-12eb1.appspot.com',
    measurementId: 'G-ZT6HYVRLBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0zv588huUFnr7bnwVfy_hPEqIwYGdbFk',
    appId: '1:425547129915:android:88b89a8dd7566e3008e81e',
    messagingSenderId: '425547129915',
    projectId: 'btdemo-12eb1',
    storageBucket: 'btdemo-12eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM3BFUjArtiA8j8VmlteQ42n-lQfjrQLw',
    appId: '1:425547129915:ios:42ffbbf3d53dfdeb08e81e',
    messagingSenderId: '425547129915',
    projectId: 'btdemo-12eb1',
    storageBucket: 'btdemo-12eb1.appspot.com',
    iosClientId: '425547129915-ng1fp68e2j5t8iqag5g88euphojrn8pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.btdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM3BFUjArtiA8j8VmlteQ42n-lQfjrQLw',
    appId: '1:425547129915:ios:42ffbbf3d53dfdeb08e81e',
    messagingSenderId: '425547129915',
    projectId: 'btdemo-12eb1',
    storageBucket: 'btdemo-12eb1.appspot.com',
    iosClientId: '425547129915-ng1fp68e2j5t8iqag5g88euphojrn8pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.btdemo',
  );
}
